export const getTheme = ({ colors }) => {
    return {
        token: {
            colorPrimary: colors.primary_60,
            colorPrimaryHover: colors.primary_70,
            colorPrimaryActive: colors.primary_80,

            colorTextBase: colors.grey_100,
            colorText: colors.grey_100,
            colorTextDescription: colors.grey_50,
            colorTextHeading: colors.grey_100,
            colorTextSecondary: colors.grey_70,
            colorTextTertiary: colors.grey_50,
            colorBgContainer: '#ffffff',
            controlItemBgHover: colors.grey_2,
            colorBorder: colors.grey_10,
            colorBorderSecondary: colors.grey_5,
            colorSplit: colors.grey_2,

            colorErrorText: colors.error_120,
            colorErrorTextActive: colors.error_120,
            colorErrorTextHover: colors.error_120,

            colorLink: colors.primary_60,
            colorLinkHover: colors.primary_60,
            colorLinkActive: colors.primary_60,

            colorSuccessText: colors.success_120,
            colorSuccess: colors.success_120,

            colorWarningText: colors.yellow_120,

            fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',

            fontSize: 14,
            fontSizeLG: 16,
            fontSizeSM: 12,

            colorBgContainerDisabled: colors.grey_10,
            colorTextDisabled: colors.grey_40,

            boxShadow: '0px 2px 40px 0px rgba(136, 136, 136, 0.20)',
        },
        components: {
            Button: {
                defaultBorderColor: colors.grey_10,
                defaultBg: colors.pure_100,
                defaultHoverBg: colors.grey_5,
                defaultHoverBorderColor: colors.grey_5,
                defaultActiveBg: colors.primary_10,
                defaultActiveBorderColor: colors.primary_10,
                defaultColor: colors.grey_100,
                defaultHoverColor: colors.grey_100,
                defaultActiveColor: colors.grey_100,
                borderColorDisabled: colors.grey_10,
                ghostBg: colors.primary_80,
            },
            Checkbox: {
                colorPrimary: colors.primary_60,
                colorPrimaryBorder: colors.primary_60,
                colorPrimaryHover: colors.primary_60,
                colorPrimaryActive: colors.primary_60,
                colorPrimaryDisabled: colors.primary_20,
                colorBgContainerDisabled: colors.pure_100,
                colorBorderDisabled: colors.grey_30,
                colorBorder: colors.grey_30,
                colorWhite: colors.pure_100,
            },
            Tree: {},
            Radio: {},
            Badge: {
                dotSize: 6,
                indicatorHeight: 16,
                textFontSize: 10,
            },
            Breadcrumb: {
                itemColor: colors.grey_50,
                lastItemColor: '#102B46',
                linkColor: colors.grey_50,
                linkHoverColor: colors.grey_50,
                separatorColor: colors.grey_50,
                separatorMargin: 6,
                colorBgTextHover: 'transparent',
                fontSize: 12,
            },
            Modal: {
                colorBgMask: '#102B464D',
            },
            Drawer: {
                boxShadow: '0px 2px 40px 0px rgba(136, 136, 136, 0.20)',
                colorBgMask: '#102B464D',
            },
            Switch: {
                colorPrimary: colors.primary_10,
                colorPrimaryHover: colors.primary_10,
                colorTextQuaternary: colors.grey_10,
                colorTextTertiary: colors.grey_10,
                handleShadow: 0,
                trackPadding: 0,
                handleSizeSM: 16,
                handleSize: 20,
                trackHeightSM: 10,
                trackMinWidthSM: 28,
                trackHeight: 14,
                trackMinWidth: 34,
            },
            Input: {
                borderRadius: 8,
                borderColor: 'none',
                padding: 12,
                fontFamily:
                    'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
                transition: 'all 0.2s ease',
                hoverBg: colors.pure_100,
                hoverBorderColor: colors.grey_10,
                activeShadow: 'none',
                activeBorderColor: colors.primary_20,
                focusBg: colors.grey_2,
                colorTextPlaceholder: colors.grey_50,
                colorText: colors.grey_100,
            },
            Tabs: {
                colorText: colors.grey_40,
                borderColorDefault: colors.grey_2,
                borderColorActive: colors.primary_60,
                inkBarColor: colors.grey_2,
            },
            Alert: {
                defaultPadding: 12,
                withDescriptionPadding: 12,
            },
            Notification: {},
            Tag: {
                defaultBg: colors.pure_100,
                borderRadiusSM: 32,
                borderRadius: 32,
            },
            Tooltip: {
                colorBgSpotlight: colors.pure_100,
                colorTextLightSolid: colors.grey_100,
            },
            Menu: {
                itemMarginInline: 0,
                itemBg: colors.grey_2,
                itemColor: colors.grey_60,
                itemHoverBg: colors.pure_100,
                itemActiveBg: colors.pure_100,
                itemSelectedBg: colors.pure_100,
                itemSelectedColor: colors.primary_60,
                subMenuItemBg: colors.grey_2,
                subMenuItemSelectedColor: colors.primary_60,
            },
            Collapse: {
                headerBg: colors.grey_2,
                headerPadding: '12px 20px',
            },
            Dropdown: {
                itemBg: colors.grey_2,
                itemColor: colors.grey_60,
                itemHoverBg: colors.primary_5,
                itemActiveBg: colors.primary_5,
                itemSelectedBg: colors.primary_5,
                controlItemBgHover: colors.primary_5,
                controlItemBgActive: colors.primary_5,
                controlItemBgActiveHover: colors.primary_5,
                controlItemBgActiveSelected: colors.primary_5,
            },
            Slider: {
                trackBg: colors.primary_60,
                trackHoverBg: colors.primary_60,
                dotActiveBorderColor: colors.primary_60,
                handleColor: colors.primary_60,
                handleActiveColor: colors.primary_60,
                railBg: colors.grey_20,
                railHoverBg: colors.grey_20,
                dotBorderColor: colors.grey_20,
            },
            InputNumber: {
                activeBorderColor: colors.primary_20,
                activeBg: colors.pure_100,
                handleBg: colors.pure_100,
                hoverBg: colors.pure_100,
                activeShadow: 'none',
                controlWidth: '100%',
                errorActiveShadow: 'none',
                handleBorderColor: colors.grey_20,
                handleHoverColor: colors.primary_60,
                hoverBorderColor: colors.grey_10,
                paddingBlock: 8,
                paddingInline: 12,
                paddingBlockLG: 12,
                paddingInlineLG: 16,
                warningActiveShadow: 'none',
                colorError: colors.grey_20,
                colorErrorBorderHover: colors.grey_20,
            },
        },
    };
};
