export {
  Chevrondown,
  Tick,
  Fail,
  Success,
  Search,
  Add,
  Edit as EditPencil,
  Facility as Building,
  Info as InfoCircle,
  Delete,
  Upload,
  Attachment,
  Overflow as MoreVert,
  Phone,
  Email as MailOutline,
  Back as ChevronLeft,
  Chevronright as ChevronRight,
  Doc as DocIcon,
  List as ListIcon,
  Help as HelpIcon,
  Notifications as NotificationIcon,
  Link,
  Linkoff,
} from '@onehaul/ui/icons';
